### ISSUE TITLE
Unsound implementation of `conv_to_u64`

### ISSUE THREAD

**Issue by shinmao** [Arkaeriit/unicode_converter#1]
### The source of unsoundness
Hi, we found that the function `conv_to_u64` has an unsound implementation:
https://github.com/Arkaeriit/unicode_converter/blob/12bbcf81698e8f55cff7dfc00e1b7b4583a484dc/src/endian_aware_byte_streamer.rs#L28-L33
At line 30, the code would created a misaligned pointer by casting, and deref it at line 33. Misaligned pointer dereference is kind of undefined behavior and should be avoided in safe function.

### To reproduce the bug
Simply running `cargo test` could trigger the undefined behavior in the test case `endian_aware_byte_streamer::test_cut_int`
```
running 20 tests
test cesu_8::test_utf_32_glyph_to_cesu_8 ... ok
test cesu_8::test_utf32_to_cesu_8_and_back ... ok
test endian_aware_byte_streamer::test_from_bytes ... ok
test test::fancy_codepoints ... ok
test test::test_null ... ok
test test::testing_string_conv ... ok
test utf_16::test_utf_16_to_utf_32_and_back ... ok
test utf_1::test_utf_32_to_utf_1_and_back ... ok
test utf_1::test_u_v ... ok
test utf_1::test_utf_32_to_utf_1_raw ... ok
test utf_32::test_data_content ... ok
test utf_8::str_to_utf_8_and_back ... ok
test utf_8::test_utf_32_to_utf_8_and_back ... ok
test utf_8::test_utf_32_to_utf_8_and_back_plus ... ok
test utf_8::test_utf_32_to_utf_8_raw ... ok
thread 'endian_aware_byte_streamer::test_cut_int' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7fe553ffe3b6', src/endian_aware_byte_streamer.rs:33:19
```

**Comment by Arkaeriit** [comment]
Thank you very much for raising this issue. I was foolishly using some platform-dependent behavior.

Commit c80eb0f should fix the issue.

**Comment by shinmao** [comment]
Thanks for the quick response. Our tool showed that it fixes the issue.

**Comment by Arkaeriit** [comment]
And thank you for showing me where the bug was. If you don't mind me asking, what are you using this crate for?

**Comment by shinmao** [comment]
We are testing our bug detector on crates.io. Hope that could help developers find potential issues in their crate.

**Comment by Arkaeriit** [comment]
Well, it helped me. ;)

**Comment by shinmao** [comment]
Good to hear it. Would you mind me to send a PR to rustsec ;)

**Comment by Arkaeriit** [comment]
I am not sure I understand what you mean. Could you clarify?

**Comment by shinmao** [comment]
[RustSec](https://rustsec.org/advisories/) could help people who use the crate on crates.io know when to update their crate. So if someone uses `unicode_converter`, `cargo check` could tell them there is an unsound implementation and update to the latest version.

**Comment by Arkaeriit** [comment]
Then you should totally do it. I don't think a lot of people use that crate but better safe than sorry.

**Comment by shinmao** [comment]
Yup. Agree with you. This is just to encourage developers to fix the bug and avoid risk in case.
